version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
      - 9004:9000
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    volumes:
      - ./data.sql:/usr/local/etc/share/data.sql
      - ./schema.sql:/usr/local/etc/share/schema.sql
      - ./initdb.sh:/usr/local/etc/share/initdb.sh
